name: Lint primarily with ESLint
on: 
  push:
    branches:
      - main
  pull_request:

jobs:

  ESLint-Prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Install our packages
        run: yarn install

      - name: Run ESLint
        run:  yarn eslint --ext ts,tsx .

      - name: Run Prettier --check
        run:  yarn prettier --check "**/*.{js,jsx,ts,tsx}"

      - name: Typescript
        run: yarn tsc --noEmit
